path: /root/autodl-tmp/road_damage_exp/datasets_yolo_ch4/real_plus_ours_200
train: images/train
val: images/val
test: images/test

names:
  0: D00_longitudinal_crack
  1: D10_transverse_crack
  2: D20_alligator_crack
  3: D40_pothole
