path: /root/autodl-tmp/road_damage_exp/datasets_cross_domain/japan_yolo
train: images/test
val: images/test
test: images/test

names:
  0: D00_longitudinal_crack
  1: D10_transverse_crack
  2: D20_alligator_crack
  3: D40_pothole
